apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvc
  namespace: jenkins
spec:
#  volumeMode: Block
  accessModes:
#  - ReadWriteOnce
  - ReadWriteMany
  storageClassName: longhorn-retain-sc
#  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
#  volumeName: longhorn-pv1
#  volumeName: pvc-89d19576-3233-4bbd-8790-37cddac684dd
