apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pod-home-dir-pvc
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn-retain-sc
  resources:
    requests:
      storage: 0.5Gi
