stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: freddyiw/my-pet-clinic-3
  DOCKER_TAG: latest

# Build stage
build_job_1:
  stage: build
  image: gradle:7.6-jdk17
  services:
    - docker:dind
  script:
    - ./gradlew build
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

# Deploy stage
deploy_job_1:
  stage: deploy
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
  script:
    - |
      ssh $EC2_USER@$EC2_HOST << EOF
        docker pull $DOCKER_IMAGE:$DOCKER_TAG
        docker stop c-my-pet-clinic-3 || true
        docker rm c-my-pet-clinic-3 || true
        docker run -d --name c-my-pet-clinic-3 -p 8081:8080 $DOCKER_IMAGE:$DOCKER_TAG
      EOF
