apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
reclaimPolicy: Retain
volumeBindingMode: Immediate
